login_app:
  build: .
  dockerfile: Dockerfile
  env_file: secrets.env
  command: mix phoenix.server
  environment:
    - MIX_ENV=dev
    - PORT=4000
  volumes:
    - .:/app
  ports:
    - "4000:4000"
